### ISSUE TITLE
Nudging mismatch

### ISSUE THREAD

**Issue by jchylik** [ARM-Development/comble-mip#35]
There seems to mismatch between the forcing files (and scripts) on one side and the case description on the other.
One says to nudge, the other NOT to nudge. 

The case description says:
**_Nudging | None (not required)_**

However the forcing file _COMBLE_INTERCOMPARISON_FORCING_V2.3.nc_ includes time-dependent nudging.

**Comment by jchylik** [comment]
Investigating the issue further:

The script for generating the forcing file nudging as True [create_comble_forcing_v2.3.ipynb L231--233](https://github.com/ARM-Development/comble-mip/blob/main/notebooks/forcing/create_comble_forcing_v2.3.ipynb?short_path=7a72944#L231)
```
  do_u_v_nudge = True
  do_th_qv_nudge = True
  do_subsidence = True
```
and then fills the variables with non-zero arrays at [create_comble_forcing_v2.3.ipynb L1514--1524](https://github.com/ARM-Development/comble-mip/blob/main/notebooks/forcing/create_comble_forcing_v2.3.ipynb?short_path=7a72944#L1514)
```
if do_u_v_nudge:
    u_nudging[:] = unudgei
    v_nudging[:] = vnudgei

if do_th_qv_nudge:
    theta_nudging[:] = tnudgei
```

**Comment by twjuliano** [comment]
@jchylik Thank you for your question. Closing this issue since it was discussed in the COMBLE MIP Check-In meeting on 1/17/24.

For those who see this and were not present at the meeting, please refer to the 'Main Model Configuration' page on the project website for model specifications. Here is the specification for large-scale forcing:

![image](https://github.com/ARM-Development/comble-mip/assets/46979614/efbe230a-49db-4337-a30a-8eaabdb0cd15)

We note that the nudge fields are included in the forcing file to facilitate: (1) comparison with the ERA5 fields and (2) sensitivity simulations. **The baseline specification does not call for nudging of any fields.**

Thanks,
Tim

**Comment by jchylik** [comment]
>  The baseline specification does not call for nudging of any fields.

Yes, but the forcing file is **_contradicting_** that. There are arrays `u_nudging, v nuding ... `.
In such case, following DEPHY format  [(page 9 of DEPHY specification)](https://github.com/GdR-DEPHY/DEPHY-SCM/blob/master/DEPHY-SCM_CommonFormat_v1.0.pdf), the following global attributes should be included:
```
 nudging_u       = 0
 nudging_v       = 0
 nudging_w       = 0
 nudging_theta   = 0
 nudging_qv      = 0
```

**Comment by jchylik** [comment]
> Thanks for letting us know about those global attributes; I was not aware of these.

To be honest, I originally wrote a conversion script just following the documentation. 

Still, alternative option would be to remove the nudging variables from the forcing file.

**Comment by fridlind** [comment]
Tim, we should place a note somewhere on the main page why we decided to include the nudging variables:

(1) sensitivity test is very easy (as we did during devel), already re-gridded for people who want to nudge winds
(2) readily available to plot against them as quasi-observational data (ERA5)

From: Jan Chylik ***@***.***>
Reply-To: ARM-Development/comble-mip ***@***.***>
Date: Wednesday, January 17, 2024 at 12:52 PM
To: ARM-Development/comble-mip ***@***.***>
Cc: "Fridlind, Ann (GISS-6110)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [ARM-Development/comble-mip] Nudging mismatch (Issue #35)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Thanks for letting us know about those global attributes; I was not aware of these.

To be honest, I originally wrote a conversion script just following the documentation.

Still, alternative option would be to remove the nudging variables from the forcing file.

**Comment by twjuliano** [comment]
@fridlind I agree this information is important to have on the website, but do we want to put that on the main page? Maybe instead on the 'Main Model Configuration' page?

**Comment by fridlind** [comment]
@twjuliano That sounds good to me. Do you want to take the lead on that?

**Comment by twjuliano** [comment]
> @twjuliano That sounds good to me. Do you want to take the lead on that?

@fridlind Sure, I'll take care of that

**Comment by anddebol** [comment]
@twjuliano should the conversion scripts from dephy [to WRF](https://github.com/ARM-Development/comble-mip/blob/7c1840ef86dde02db08fdca09589e3146d305be7/notebooks/conversion/convert_comble_dephy_forcing_to_WRF_LES_forcing.ipynb) and [to DHARMA](https://github.com/ARM-Development/comble-mip/blob/7c1840ef86dde02db08fdca09589e3146d305be7/notebooks/conversion/convert_comble_dephy_forcing_to_DHARMA_LES_and_ModelE3_SCM_forcing.ipynb) be updated to use v2.4 (currently 2.3)? Not that is changing anything

**Comment by twjuliano** [comment]
@anddebol thanks for letting us know. The v2.4 output file contents are identical to those of v2.3 with the exception of some global attributes, but yes, we should update these to use v2.4 to avoid confusion. @fridlind @floriantornow
