### ISSUE TITLE
Units in aerosol emission specification

### ISSUE THREAD

**Issue by anddebol** [ARM-Development/comble-mip#60]
On the page [Specifying Surface Aerosol Emissions for Simulations with Multi-Modal Aerosol](https://arm-development.github.io/comble-mip/notebooks/setup/aerosol-surface.html#) the last equation is called for SST in  K, but in Jaegle et al. (2011) the corresponding equation (eq. 4 in the paper) calls for SST in C with same coefficients as on the webpage.
![image](https://github.com/ARM-Development/comble-mip/assets/4727244/59680f4c-0ff0-493c-90dc-fbd537c8a73c)

**Comment by floriantornow** [comment]
That is indeed a mistake on the page and I'll correct it now (please use SST in degC). Thank you for pointing this out.

Best,
Florian
